image:
  repository: docker.io/nimrodoron/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

webhookConfig:
  serverPort: 443

disableControllers: []
