image:
  repository: docker.io/nimrodoron/gardener-extension-hyper
  tag: 0.15.0
  pullPolicy: IfNotPresent

resources: {}

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
